 
 POST http://localhost:9000/login
 Content-Type: application/json 


 
    {
      
      "email":"mins",
    "password":"12345"
    

 }

###

POST http://localhost:9000/signUp
 Content-Type: application/json 


 
    {
      "name":"zack",
      "email":"mins",
    "password":"12345"

 }

###

GET http://localhost:9000/B